version: '3'

services:
  web:
    build: .
    volumes:
      - type: bind
        source: .
        target: /app
    ports:
      - "4000:4000"
    environment:
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=db
      - DB_NAME=ski_map
    depends_on:
      - db
    command: tail -f /dev/null
    # command: ./run.sh

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ski_map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data: