version: '3'

services:
  app:
    build:
      context: ../
      dockerfile: Dockerfile
    ports:
      - "4000:4000"
    environment:
      - PORT=4000
      - BINDING=0.0.0.0
      - DB_USERNAME=postgres
      - DB_PASSWORD=postgres
      - DB_HOSTNAME=db
      - DB_NAME=ski_map
    volumes:
      - ../:/app
    depends_on:
      - db
    command: sleep infinity

  db:
    image: postgis/postgis
    ports:
      - "5432:5432"
    volumes:
      - type: volume
        source: db-data
        target: /var/lib/postgresql/data
    environment:
      - POSTGRES_DB=ski_map
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres

volumes:
  db-data: